name: chattao_app
description: A chat app created by taotao.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2+1
  firebase_auth: ^0.6.2+1
  google_sign_in: ^3.0.5
  cached_network_image: "^0.4.1"
  firebase_storage: 1.0.2
  fluttertoast: ^2.0.8
  shared_preferences: ^0.4.2
  image_picker: ^0.4.10
  intl: ^0.15.7
  vercoder_inputer: ^0.4.0
  firebase_messaging: ^2.0.2
  flutter_redux: ^0.5.2
  redux: ^3.0.0
  # image: ^2.0.4
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/img_not_available.jpeg
     - images/gifs/mimi/mimi1.gif
     - images/gifs/mimi/mimi2.gif
     - images/gifs/mimi/mimi3.gif
     - images/gifs/mimi/mimi4.gif
     - images/gifs/mimi/mimi5.gif
     - images/gifs/mimi/mimi6.gif
     - images/gifs/mimi/mimi7.gif
     - images/gifs/mimi/mimi8.gif
     - images/gifs/mimi/mimi9.gif

     - images/gifs/doubi/doubi1.gif
     - images/gifs/doubi/doubi2.gif
     - images/gifs/doubi/doubi3.gif
     - images/gifs/doubi/doubi4.gif
     - images/gifs/doubi/doubi5.gif
     - images/gifs/doubi/doubi6.gif
     - images/gifs/doubi/doubi7.gif
     - images/gifs/doubi/doubi8.gif
     - images/gifs/doubi/doubi9.gif

     - images/gifs/miao/miao1.gif
     - images/gifs/miao/miao2.gif
     - images/gifs/miao/miao3.gif
     - images/gifs/miao/miao4.gif
     - images/gifs/miao/miao5.gif
     - images/gifs/miao/miao6.gif
     - images/gifs/miao/miao7.gif
     - images/gifs/miao/miao8.gif
     - images/gifs/miao/miao9.gif

     - images/icons/chats_active.png
     - images/icons/chats_outline.png
     - images/icons/contacts_active.png
     - images/icons/contacts_outline.png
     - images/icons/discover_active.png
     - images/icons/discover_outline.png
     - images/icons/profile_active.png
     - images/icons/profile_outline.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
